### ISSUE TITLE
InstanceCreationException when passing mix of nullable and non-nullable parameters

### ISSUE THREAD

**Issue by aradomski** [InsertKoinIO/koin#1740] opened 2023-12-22 22:23 UTC
When I'm passing mix of nullable and non-nullable parameters using `parameterArrayOf`, `InstanceCreationException` appears because koin attempts to cast null as next parameter type

**To Reproduce**
See snippet

**Expected behavior**
When using method `getOrNull` null is returned, when null was provided and internal index of `ParametersHolder` is incremented . Next call `get` or `getOrNull` should provide appropriate item from array provided by `parameterArrayOf`

**Koin module and version:**
 `koin-core:3.5.0`

**Snippet or Sample project to help reproduce**
Tested on android

```
fun initKoin(appDeclaration: KoinAppDeclaration = {}) =
    startKoin {
        appDeclaration()
        modules(viewModelModule)
    }

val viewModelModule = module {
    factory {
        val projectId: String? = it.getOrNull()
        val workspaceId: String = it.get()
        val imageId: String? = it.getOrNull()
        val someData:SomeData = it.get()
        SomeViewModel(projectId, workspaceId, imageId, someData)
    }
}
```
```
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            val viewModel: SomeViewModel = GlobalContext.get().get {
                val projectId: String? = "ProjectId"
                val workspaceId: String = "WorkspaceId"
                val imageId: String? = null
                val someData: SomeData = SomeData("Some data")
                parameterArrayOf(projectId, workspaceId, imageId, someData)
            }

            Text(
                text = "projectId=${viewModel.projectId} " +
                        "workspaceId = ${viewModel.workspaceId} " +
                        "imageId = ${viewModel.imageId} " +
                        "someData = ${viewModel.data} "
            )
        }
    }

```

**Comment by aradomski** [comment] 2023-12-22 22:27
Proposition of solution #1741

**Comment by Nek-12** [comment] 2023-12-25 08:47
Duplicate of #1456

**Comment by Nek-12** [comment] 2024-05-24 04:12
@arnaudgiuliani don't tell me you followed the accompanist footsteps and added this garbage bot. Please remove it as all open issues are still valid.

**Closed** 2024-05-31 21:54 UTC
Labels: status:wontfix

**Comment by Nek-12** [comment] 2024-05-31 21:58
@arnaudgiuliani this is not completed
