### ISSUE TITLE
[koin-android-compose] Broken view model factory when migrating from 3.5.0 -> 3.5.3/3.5.4

### ISSUE THREAD

**Issue by javiercamarenatriguero** [InsertKoinIO/koin#1844] opened 2024-04-08 11:57 UTC
**Describe the bug**
I recently upgraded to koin-androidx-compose:3.5.4 from koin-androidx-compose:3.5.0 and the Automation Test stat failing because of this error:
```
Caused by: org.koin.core.error.ClosedScopeException: Scope '_root_' is closed
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:213)
        at org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:25)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:184)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:150)
        at org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel(GetViewModel.kt:44)
```
Tested it just affect to `koin-android-compose` library as the rest of koin libraries are not affecting the Android Test results.
**To Reproduce**
1. Run Automation Test with more than 1 test cases
2. See error after the second TestCase starts the execution.

**Expected behavior**
It should not fail as v3.5.0 version.

**Koin module and version:**
`koin-androidx-compose:3.5.3` & `koin-androidx-compose:3.5.4`

**Comment by arnaudgiuliani** [comment] 2024-04-10 15:49
Can you detail it a bit more?

**Comment by javiercamarenatriguero** [comment] 2024-04-11 06:25
Thanks @arnaudgiuliani ! Sure, The issue just affects when the `koin-androidx-compose` is upgraded from v3.5.0 -> v3.5.3/4.  The code contains some Automation Test in Espresso, and for some reason the second Test Case of the same Test Class fails when the ViewModelFactory tries to get the instance of the ViewModel. In order to provide more information, this is the `KoinTestRule` used on the Test Class (based on tutorials):
```
class KoinTestRule(
    private val modules: List<Module> = emptyList()
) : TestWatcher() {

    private val modulesByDefault = listOf(dataModule, useCaseModule, viewModelModule, appModule)
    override fun starting(description: Description) {
        startKoin {
            androidContext(InstrumentationRegistry.getInstrumentation().targetContext.applicationContext)
            modules(modulesByDefault + modules)
        }
    }

    override fun finished(description: Description) {
        stopKoin()
    }
}
```
And this is the invocation on the Test Class:
```
private val instrumentedTestModule = module {
        factory { getMockDataLocalSource() }
        factory { getMockQuestions(questionJson) }
        ...
    }

    override val koinTestRule: KoinTestRule
        get() = KoinTestRule(
            modules = listOf(instrumentedTestModule)
        )
```
The first TestCase works fine, but the second one fails on this. It happens to all the Test Classes. It was working fine until now. Thanks in advance

**Comment by kasim-canol-sz** [comment] 2024-04-22 09:42
@arnaudgiuliani Do you have any updates regarding this issue? Our tests are also affected by the same issue, therefore we're currently not able to update the koin version.

**Comment by javiercamarenatriguero** [comment] 2024-05-02 06:51
Hi @arnaudgiuliani, any update about this issue? Thanks in advance

**Comment by arnaudgiuliani** [comment] 2024-05-03 15:37
weird, seems that VM factory is invoked after scope closing 🤔

**Comment by arnaudgiuliani** [comment] 2024-05-03 15:39
can anyone help by providing a test project for that? @kasim-canol-sz @javiercamarenatriguero

**Comment by dazza5000** [comment] 2024-07-31 17:11
We are experiencing this after upgrading too. Did anyone find a workaround?

**Comment by GerardPaligot** [comment] 2024-08-18 07:09
I've the exact same issue. I can work on a small test project if it is necessary, but the issue is present in one of my OSS project (https://github.com/GerardPaligot/conferences4hall/tree/test/schedules). In this project, I'm using koin `3.6.0-Beta4` and I'm writing instrumented test cases in `theme-m3/schedules/schedules-sample` module with two test classes: `FilteringScheduleTest` and `ScheduleDetailsTest`.

These two classes is using `org.koin.test.KoinTestRule` to override koin modules used in the `MainActivity` of the sample module.

```kotlin
@get:Rule
val koinTestRule = KoinTestRule.create {
    androidContext(InstrumentationRegistry.getInstrumentation().targetContext.applicationContext)
    modules(listOf(scheduleModule, instrumentedModule))
}
```

If I'm executing one by one test classes, there is no issue but if I'm merging these test classes in only one file or if I'm executing these classes in the same JVM (run at the package level), I got the error:

```bash
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:590)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
... 1 more
Caused by: org.koin.core.error.ClosedScopeException: Scope '_root_' is closed
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
at org.koin.core.scope.Scope.get(Scope.kt:213)
at org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:25)
at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.android.kt:158)
at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release(ViewModelProviderImpl.kt:67)
at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release$default(ViewModelProviderImpl.kt:47)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:91)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:109)
at org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel(GetViewModel.kt:44)
at org.gdglille.devfest.android.theme.m3.schedules.feature.ScheduleGridVMKt.ScheduleGridVM(ScheduleGridVM.kt:82)
at org.gdglille.devfest.android.theme.m3.schedules.feature.ScheduleGridAdaptiveKt$ScheduleGridAdaptive$1.invoke(ScheduleGridAdaptive.kt:39)
at org.gdglille.devfest.android.theme.m3.schedules.feature.ScheduleGridAdaptiveKt$ScheduleGridAdaptive$1.invoke(ScheduleGridAdaptive.kt:38)
```

It starts from `ScheduleGridVM` class that inject its `ViewModel` but it is probably because it is the entry point of the injection. I think the root cause is probably more the koin context closed after every test case but the same scope context reused between every test cases.

I hope it can help. Available to carry out further investigations.

**Comment by GerardPaligot** [comment] 2024-08-18 20:46
After some deeper investigations, it seems that `LocalKoinScope` local composition isn't updated between two test cases (when there are executed in the same process). This local is used by the function `currentKoinScope` and this function, by `koinViewModel` function. That is the root cause of this issue.

I don't have a fix but if you need a workaround, you can force the correct scope inside your `koinViewModel` call:

```kotlin
viewModel: ScheduleGridViewModel = koinViewModel(
    scope = KoinPlatformTools.defaultContext().get().scopeRegistry.rootScope
)
```

I hope it can help someone here!

**Comment by javiercamarenatriguero** [comment] 2024-09-04 14:09
Hi there, after applying the given solution (setting the scope) it still fails on the second test:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:562)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
... 1 more
Caused by: org.koin.core.error.ClosedScopeException: Scope '_root_' is closed
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
at org.koin.core.scope.Scope.get(Scope.kt:213)
```
Hope it could help to find a solution.
Thanks in advance.

**Comment by arnaudgiuliani** [comment] 2024-09-09 16:46
Ok, let me check it again. I missed the issue 👍

**Comment by arnaudgiuliani** [comment] 2024-09-12 10:18
> After some deeper investigations, it seems that `LocalKoinScope` local composition isn't updated between two test cases (when there are executed in the same process). This local is used by the function `currentKoinScope` and this function, by `koinViewModel` function. That is the root cause of this issue.
> 
> I don't have a fix but if you need a workaround, you can force the correct scope inside your `koinViewModel` call:
> 
> ```kotlin
> viewModel: ScheduleGridViewModel = koinViewModel(
>     scope = KoinPlatformTools.defaultContext().get().scopeRegistry.rootScope
> )
> ```
> 
> or use `KoinContext` composable at the root level of your component tree to force the scope update:
> 
> ```kotlin
> setContent {
>   KoinContext(context = KoinPlatformTools.defaultContext().get()) {
>     // Your composable tree
>   }
> }
> ```
> 
> I hope it can help someone here!

Seems linked to [recent](https://github.com/InsertKoinIO/koin/issues/1900)

**Comment by arnaudgiuliani** [comment] 2024-09-12 15:58
let's follow up https://github.com/InsertKoinIO/koin/issues/1900 - Fix around base Scope API and Local Composition should do the thing.

**Closed by arnaudgiuliani** 2024-09-12 15:58 UTC
Labels: type:issue, status:checking
