### ISSUE TITLE
3.2.0 -> 3.2.1 ... WTF?

### ISSUE THREAD

**Issue by valeriyo** [InsertKoinIO/koin#1443] opened 2022-09-27 04:47 UTC
Pardon my French, but WTF is happening with Koin these days?

3.2.1 broke compatibility with 3.2.0:
 - delegate `activityRetainedScope()` replaced by method `createActivityRetainedScope()`
 - `AndroidScopeComponent` completely changed, became incompatible with `KoinScopeComponent` because of `scope`.

That's not how things are done, people.

**Comment by To6i** [comment] 2022-09-27 11:10
I have to agree with that completely.

We have seen incompatible / breaking changes with minor and even patch releases of Koin multiple times now. It makes updating the library an absolute nightmare. Koins version numbers have no meaning at all anymore. There is a reason why [semantic versioning](https://semver.org/) has been created in the first place.

We love Koin as a library, but the release handling makes it hard to stick to it.

**Comment by Pfoerd** [comment] 2022-09-27 13:00
Unfortunately I have to agree 100% too!

we're using Koin in a large scale Android project with multiple 100k locs now for more multiple years and we actually love the concepts of Koin! Plagued by code generation with Dagger and bytecode manipulation/reflection orgies with Guice, Koin's straight-forward approach finally promises a maintainable, fast and robust solution for dependency injection in large projects.

But unfortunately the unsteady further development makes Koin now almost unusable in productive applications. Every update in the last years came with big problems for us: 
* a lot of migration effort because of breaking changes
* a lot of pain because of implicit behavioral changes
* a lot of regressions that have to be found and fixed with great effort

We have now reached a point where we are seriously considering whether a migration away from Koin to an in-house developed alternative or even back to Guice/Dagger/Hilt ( 😢 ) is a more effective option than jumping from bug to bug with each update.

Please do not get this wrong: we love Koin and the ideas behind it and really appreciate all contributors' work on it but currently it is really hard to argue for the usage of Koin in a large project!

What we would need in Koin:
* strict semantic versioning
* more tests to avoid regressions, e.g. for Android specifics
* focus on fixing bugs
* a concept for backward compatibility
* a clear roadmap for breaking changes / major versions

**Comment by arnaudgiuliani** [comment] 2022-10-11 16:23
Hey there, 

Thanks, your feedback is really precious. 3.2.x was updated with minor changes. 

From the last feedback, `activityRetainedScope()` was hard to catch with its lazy behavior. And then, lifecycle mapping was not good. The 3.2.2 proposal was to propose eager API. This change is clearly too breaking :/  my bad

I will prepare a patch in 3.2.3 to revert this.

**Comment by arnaudgiuliani** [comment] 2022-10-11 16:34
proposal -> 3.2.3 to revert "new" createActivityRetainedScope. If I can propose it without touching the current base, I will keep it.
Else it will be pushed in 3.3.x

**Closed** 2022-10-18 14:16 UTC
Labels: status:checking, important 🔥, regression 💥
