### ISSUE TITLE
java.lang.NoSuchMethodError with kotlin 1.6

### ISSUE THREAD

**Issue by krottv** [InsertKoinIO/koin#1242] opened 2021-12-06 11:29 UTC
**Describe the bug**
```
java.lang.NoSuchMethodError:
No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in
```

**To Reproduce**
1. Set kotlin 1.6 in project
2. Call 

```
    startKoin {

            if (BuildConfig.DEBUG)
                androidLogger()
                
            // declare modules
            androidContext(this@App)
            modules(...)
     }
```

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.1.4`

**Comment by egorikftp** [comment] 2021-12-06 14:37
Duplicate of https://github.com/InsertKoinIO/koin/issues/1188

**Comment by Jesil-OT** [comment] 2021-12-14 10:30
works for me, Thanks

**Comment by Jesil-OT** [comment] 2021-12-14 10:30
works for me, Thanks

**Comment by tomtaila** [comment] 2022-01-21 23:03
Yeah I have the same issue

**Comment by Arman10000** [comment] 2022-01-25 12:13
The method helped me
`startKoin { androidLogger(Level.ERROR) }`
Or not to use `androidLogger()`

**Comment by arnaudgiuliani** [comment] 2022-06-27 13:22
is outdated with Koin 3.2.0.

**Closed by arnaudgiuliani** 2022-06-27 13:22 UTC

**Comment by vuuygur** [comment] 2023-02-23 16:52
add where ?

**Comment by arnaudgiuliani** [comment] 2023-03-08 08:13
Time API has been ported back. Since Koin 3.2 we are less impacted by Kotlin upgrades
