### ISSUE TITLE
Publish to Maven Central?

### ISSUE THREAD

**Issue by madhead** [InsertKoinIO/koin#1004] opened 2021-02-03 22:09 UTC
[Starting from May 1, 2021 JCenter will stop working](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter). I was looking for official Koin artifacts in Maven Central and didn't find any, only [some repackaged ones](https://search.maven.org/search?q=koin). Do you publish only to JCenter? Are there any plans to move away?

**Describe the solution you'd like**
Official Koin artifacts should be available outside of JCenter, preferably in Maven Central.

**Describe alternatives you've considered**
 - [JitPack](https://jitpack.io)
 - [GitHub Packages](https://docs.github.com/en/packages)

**Target Koin project**
All of them.

**Comment by arnaudgiuliani** [comment] 2021-02-04 09:48
Maven central also. Many Kotlin libs will go on that.

**Comment by paristote** [comment] 2021-02-04 14:43
Will you republish previous releases too? Otherwise they won't available anymore after May 1st, which will make it impossible to reproduce old builds.

**Comment by arnaudgiuliani** [comment] 2021-02-05 11:38
Yes, thanks a good point 🤔

**Comment by arnaudgiuliani** [comment] 2021-03-03 13:54
Versions are deploying on maven central: https://search.maven.org/search?q=io.insert-koin

Note that the new maven group id is `io.insert-koin` instead of `org.koin`. Others version will follow

**Comment by madhead** [comment] 2021-03-03 15:01
BTW, you may find https://github.com/gradle-nexus/publish-plugin useful to automatically close and release staging repositories in OSSRH.

**Comment by arnaudgiuliani** [comment] 2021-03-03 16:52
Yes, I know. will be added for next publish 👍

**Comment by DaphnevdVeeke** [comment] 2021-03-03 18:13
Right now I'm using `"org.koin:koin-android:2.2.2"` and `"org.koin:koin-android-viewmodel:2.2.2"` in my app, but I have issues updating the last one since I can't find it here https://search.maven.org/search?q=io.insert-koin. When I use this combination: `"io.insert-koin:koin-android:3.0.1-alpha-6"` and `"org.koin:koin-android-viewmodel:2.2.2"` I get a lot of duplicate class errors. When I don't use the ViewModel library I can't use `viewModel()` or `androidContext` no more. I also tried combining the library with other libraries I found on the Maven website, but none of those make `viewModel()` or `androidContext` resolvable. Have they become deprecated? I can't find any information on that.  Is there an alternative to use? Or is it included in another library?

**Comment by jameswald** [comment] 2021-03-03 18:28
It sounds like @arnaudgiuliani is planning to deploy 2.2.2 to Maven Central as well as other previous versions. We're in the same situation now that we've dropped jcenter from our build.

**Comment by DaphnevdVeeke** [comment] 2021-03-03 18:33
@jameswald I think you might have interpreted my question wrong (or I interpreted your answer wrong). I don't specifically need version 2.2.2 of any library, the newer the better 😄 

But I'm not sure what @arnaudgiuliani meant by "other versions will follow". Other versions of the libraries that are currently on there, or other versions like `-viewmodel` and `-architecture`. So my question is whether a version of `"koin-android-viewmodel"` will be available on Maven too, it doesn't really matter which version.

**Comment by xsveda** [comment] 2021-03-04 06:57
@DaphnevdVeeke `koin-android-viewmodel` artifact does not exist anymore in newer versions, it was merged to `koin-android` in `3.0.1-alpha03`. Thats the root of duplications you experience, the `io.insert-koin:koin-android:3.0.1-alpha-6` artifact should be all you need.
See https://github.com/InsertKoinIO/koin/blob/master/CHANGELOG.md

**Comment by DaphnevdVeeke** [comment] 2021-03-04 07:34
@xsveda I saw that, but then how to we use `org.koin.android.viewmodel.dsl.viewModel` or an equivalent reference?

**Comment by matsujun** [comment] 2021-03-09 13:04
Not only previous version but also current (stable) version is not exist on maven central...
There are only alpha version on maven central...

**Comment by arnaudgiuliani** [comment] 2021-03-09 13:25
current is beta-1: https://search.maven.org/search?q=io.insert-koin

**Comment by matsujun** [comment] 2021-03-10 02:40
Beta is NOT stable version.

**Comment by jakoss** [comment] 2021-03-15 09:04
I think the historical versions are crucial for a lot of people. Not everybody can upgrade just like that

**Comment by arnaudgiuliani** [comment] 2021-03-17 16:49
sure, I will repush them for Q2.

**Comment by dendrocyte** [comment] 2021-04-13 10:24
I ref. https://insert-koin.io/docs/setup/v3/ and change to MavenCentral, but found `stateViewModel` is not available to use.

**Comment by arnaudgiuliani** [comment] 2021-04-13 12:26
it should be available in koin-android package

**Comment by arnaudgiuliani** [comment] 2021-05-24 08:22
2.0.1, 2.1.6 & 2.2.2 have been pushed to Maven Central, as well as 3.x versions.

**Closed by arnaudgiuliani** 2021-05-24 08:22 UTC
Labels: important, status:accepted, status:check, tools

**Comment by soniamca17** [comment] 2021-05-24 13:00
Its not working I am not able to use the dependency - org.koin:koin-android:2.1.6 from mavenCentral. Please help.

**Comment by OrangeDog** [comment] 2021-05-24 13:51
@soniamca17 
> Note that the new maven group id is `io.insert-koin` instead of `org.koin`.

**Comment by jbvincey** [comment] 2021-05-31 16:40
@arnaudgiuliani the documentation https://insert-koin.io/docs/setup/v2/ is not up-to-date. It points to mavenCentral but still references the group id `org.koin`. Could you update the documentation?
Thanks in advance 🙏

**Comment by arnaudgiuliani** [comment] 2021-06-01 15:09
Arf yes. Thanks @jbvincey, it's deploying

**Comment by arnaudgiuliani** [comment] 2021-06-01 15:10
@soniamca17 the goup id is now "io.insert-koin" and not "org.koin"

**Comment by tasomaniac** [comment] 2022-01-18 12:21
In case the `koin` runtime dependency comes transitively from another dependency, the above suggestions may not be too easy to do. In case someone hits this issue, I'm leaving a solution that I found with Gradle.

It basically dynamically substitutes all of the `org.koin` dependencies with `io.insert-koin` while keeping the module name and versions intact. This might help you remove `jcenter` even if your dependency did not update koin yet.

```
    configurations.all {
        resolutionStrategy {

            dependencySubstitution {
                all {
                    val requested = this.requested as? ModuleComponentSelector
                    if (requested != null && requested.group == "org.koin") {
                        useTarget("io.insert-koin:${requested.module}:${requested.version}")
                    }
                }
            }
        }
    }
```
