### ISSUE TITLE
No definition found for class:'androidx.lifecycle.SavedStateHandle'

### ISSUE THREAD

**Issue by OleksandrGrument** [InsertKoinIO/koin#963] opened 2020-11-26 17:40 UTC
I'm using new Koin version 2.2.1 and I'm getting runtime error in viewmodel where i'm using SavedStateHandle
In previous version 2.1.6 all was fine. I used savedStateViewModel, now i'm getting crash after migration 

all I did acording to article, maybe something are missed there?
https://doc.insert-koin.io/#/koin-android/viewmodel?id=viewmodel-and-state-bundle

` Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:282)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:251)
        at org.koin.core.scope.Scope.get(Scope.kt:204)
        at com.grument.laika.di.DiManager$module$1$19.invoke(DiManager.kt:76)
        at com.grument.laika.di.DiManager$module$1$19.invoke(DiManager.kt:35)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:236) 
        at org.koin.core.scope.Scope.get(Scope.kt:204) 
        at org.koin.androidx.viewmodel.factory.StateViewModelFactory.create(StateViewModelFactory.kt:21) 
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at org.koin.androidx.viewmodel.ViewModelResolverKt.get(ViewModelResolver.kt:23) 
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:12) 
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:86) 
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:72) 
        at org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExt.kt:41) 
        at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getViewModel(FragmentExt.kt:71) 
        at com.grument.laika.view.transfer.StyleTransferFragment$$special$$inlined$viewModel$2.invoke(FragmentExt.kt:73) 
        at com.grument.laika.view.transfer.StyleTransferFragment$$special$$inlined$viewModel$2.invoke(Unknown Source:0) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at com.grument.laika.view.transfer.StyleTransferFragment.getViewModel(Unknown Source:2) 
        at com.grument.laika.view.transfer.StyleTransferFragment.initObservers(StyleTransferFragment.kt:101) 
        at com.grument.laika.view.transfer.StyleTransferFragment.onViewCreated(StyleTransferFragment.kt:42) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199) 
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2236) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2009) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1965) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861) 
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

in module
`viewModel { (image: File) -> StyleTransferViewModel(context = androidContext(), repository = get(), modelManager = get(), state = get(), image = image) }`

the class where i'm injecting
`class StyleTransferViewModel(private val context: Context,
                             private val repository: Repository,
                             private val modelManager: ModelManager,
                             state: SavedStateHandle,
                             image: File) : CommonViewModel(repository)`

in fragment 
` private val viewModel: StyleTransferViewModel by viewModel{ parametersOf(args.image) }`

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 2.2.1`

Any help apreciated

**Comment by OleksandrGrument** [comment] 2020-11-30 13:05
Hi, already resolved this issue, but with weird solution. 

Before in module was like this, all values in ViewModel constructor was passed by name 
viewModel { (image: File) -> StyleTransferViewModel(context = androidContext(), repository = get(), modelManager = get(), state = get(), image = image) }

Now I changed by order 
viewModel { (image: File) -> StyleTransferViewModel(androidContext(), get(), get(), get(), image) }

And all works well. Not sure what caused this issue, this all really very weird.

**Comment by dendrocyte** [comment] 2020-12-07 11:00
same here with @OleksandrGrument

**Comment by arnaudgiuliani** [comment] 2020-12-17 13:59
can be a problem with new default ViewModel factory 🤔

**Comment by arnaudgiuliani** [comment] 2020-12-17 13:59
it's curious that it's looking for `default` state bundle 

> .NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'

**Comment by arctouch-andrecardoso** [comment] 2020-12-29 22:08
The same problem happened to me using version 2.2.2. The only way I could make it work is by changing the ViewModel constructor params order to have the `SavedStateHandle` as the first parameter.

**Comment by jsaumellbasetis** [comment] 2020-12-30 16:26
I also get the `Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!`. In my case setting the handle as first parameter does not solve it.  

And passing the parameters by name or by position does not fix it either.

**Comment by jsaumellbasetis** [comment] 2020-12-30 16:42
I have also noticed I am not able to add the state parameter when calling `by viewModel(state = { Bundle() })`. The viewModel method does not accept a state variable and I was not able to find an import that accepts it. I am on 2.2.2.

**Comment by arctouch-andrecardoso** [comment] 2020-12-30 17:18
@jsaumellbasetis I'm using `import org.koin.androidx.viewmodel.scope.emptyState` as it is done in the example [here](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/examples/androidx-samples/src/main/java/org/koin/sample/androidx/mvvm/MVVMFragment.kt#L31).

**Comment by jsaumellbasetis** [comment] 2020-12-30 17:22
Ok sorry, I got it. I had spent several hours on this, and half an hour after writing I see that I did not have the androidx-fragment koin library, and I had the android-viewmodel instead of androix-viewmodel.  
With these changes it works now.

**Comment by antonsarmatin** [comment] 2020-12-30 18:28
Similar problem if the savedStateHandle parameter is not the first. 
Weird.

**Comment by PingForward** [comment] 2021-01-07 13:48
```
    val koinVersion = "2.2.2"
    implementation("org.koin:koin-androidx-viewmodel:$koinVersion")
    implementation("org.koin:koin-androidx-fragment:$koinVersion")
    implementation("org.koin:koin-androidx-ext:$koinVersion")
```
I saw in other issues messages about **stateViewModel/sharedStateViewModel** is it deprecated or i'm looking not at the right place?
I have sharedGraphViewModel and can't combine it with SavedStateHandle.

ViewModel
```
class CheckoutViewModel(
    val handle: SavedStateHandle,
    other staff
) : ViewModel() 

 viewModel { CheckoutViewModel(get(),....) }
```
Delegate to share viewmodel. It seems I need something like getKoin().**getStateViewModel** but it's not in the library anymore.
``` 
inline fun <reified VM : ViewModel> Fragment.sharedGraphViewModel(
    @IdRes navGraphId: Int,
    qualifier: Qualifier? = null,
    noinline initialState: BundleDefinition? = null,
    noinline parameters: ParametersDefinition? = null,
) = lazy(LazyThreadSafetyMode.NONE) {
    getKoin().getViewModel(
        qualifier = qualifier,
        state = initialState,
        owner = { ViewModelOwner.from(findNavController().getViewModelStoreOwner(navGraphId)) },
        clazz = VM::class,
        parameters = parameters
    )
}
```
And usage
```
    private val viewModel by sharedGraphViewModel<CheckoutViewModel>(R.id.navigationCheckout) {
        parametersOf(args.orderId, args.order)
    }
```
Any thoughts how to combine sharedGraphViewModel and SavedStateHandle?

[exception.TXT](https://github.com/InsertKoinIO/koin/files/5781924/exception.TXT)

**Comment by PingForward** [comment] 2021-01-07 16:15
It seems I figurre it out. Please have a look at this gist if some one needs the same functionality
[SharedGraphViewModel.kt](https://gist.github.com/PingForward/1bec024bc187b1afc8e583dd3336952b)

**Comment by josephsarz** [comment] 2021-01-08 09:10
This solved my issue https://stackoverflow.com/a/61316807/7046279

**Comment by adenisyuk** [comment] 2021-01-14 11:22
The problem is at `.koin.androidx.viewmodel.ViewModelResolver.kt`:

```
private fun <T : ViewModel> Scope.pickFactory(
        viewModelParameters: ViewModelParameter<T>,
): ViewModelProvider.Factory {
    return when {
        viewModelParameters.registryOwner != null && viewModelParameters.initialState != null -> StateViewModelFactory(this, viewModelParameters)
        else -> DefaultViewModelFactory(this, viewModelParameters)
    }
}
```
where the cause is `viewModelParameters.initialState != null`.

E.g. the wrong factory will be chosen  if the `state: BundleDefinition` passed is `null` (`DefaultViewModelFactory` instead of `StateViewModelFactory`).
That's why passing an empty state as mentioned by @arctouch-andrecardoso  (`val viewModel: MyViewModel by viewModel(emptyState())`) fixes the issue.

@arnaudgiuliani is it an expected behavior(therefore a bug in the [documentation](https://doc.insert-koin.io/#/koin-android/viewmodel?id=viewmodel-and-state-bundle)) or a bug?

**Comment by tajchert** [comment] 2021-01-14 14:02
I'm on `2.2.2` (with proper `androidx` both `fragment` and `viewmodel` extra dependencies), `SavedStateHandle` is the first parameter and I don't used `SharedGraphViewModel` - however I still get:

`Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!`

**Comment by OleksandrGrument** [comment] 2021-01-15 13:37
Also I found another weird behaviour. The order of parameters may cause this bug. When the "state" 1 or 2 in order, all working properly, but when state is as 4 by order getting this error.

**Comment by TepesLucian** [comment] 2021-01-22 13:47
I've also encountered this issue. Was working okay on `2.2.1` (which documentation lists it as the current `stable` which is a bit confusing) but after updating to `2.2.2` the app was crashing with `org.koin.core.error.NoBeanDefFoundException`. After some research I've landed on https://github.com/InsertKoinIO/koin/blob/master/CHANGELOG.md which says that `DefaultViewModelFactory` is used by default and `StateViewModelFactory` if a `state` parameter is passed so the following works for me:
```
val viewModel by viewModel<MyViewModel>(state = { Bundle.EMPTY })
```

**Comment by ALXKAY** [comment] 2021-01-29 20:57
@TepesLucian Thanks. Also you can use `emptyState()`  instead of `{ Bundle.EMPTY }`

**Comment by c-b-h** [comment] 2021-02-02 08:39
This is the signature of the `ViewModel` I had issues with:

```kotlin
class QuizViewModel(
    savedStateHandle: SavedStateHandle,
    quizId: String,
    cardId: String,
    context: Context,
    service: Service,
) : ViewModel()
```

and I defined the `viewModel` as such:
```kotlin
module {
    viewModel { (quizId: String, cardId: String) ->
        QuizViewModel(get(), quizId, cardId, get(), get())
    }
```

and consumed it like so:
```kotlin
val viewModel by viewModel<QuizViewModel>(state = emptyState()) {
        parametersOf("some id", "another id")
}

```

…without using the `emptyState()` solution I would get the same crash and I'm on `2.2.2` too. As can be noted I am both passing `savedStateHandle` **AND** other non-koin-obtained parameters.

**Comment by gmk57** [comment] 2021-02-12 12:46
@TepesLucian @ALXKAY @c-b-h  Doesn't passing `emptyState()` or `{ Bundle.EMPTY }` defeat the whole purpose of ViewModel Saved State mechanism?

I also suppose the bug in 2.2.2 deserves a [thread of its own](https://github.com/InsertKoinIO/koin/issues/1009).

**Comment by TepesLucian** [comment] 2021-02-12 15:39
@gmk57 not really since you can use that bundle to apply initial params to `SavedStateHandle` (e.g. pass a fragment argument in there as an initial state). I do agree that the documentation is missing since i needed to dig on my own in their changelog to figure out the  `emptyState()` / `{ Bundle.EMPTY }` params that i needed to pass.

**Comment by arctouch-andrecardoso** [comment] 2021-02-12 16:05
The documentation is also not clear that `SavedStateHandle` must be the first parameter

**Comment by arnaudgiuliani** [comment] 2021-03-03 13:56
Koin 3.0.1 make parameters available in the Koin graph. This means that we can resolve anything with `get()` even injection parameters.

**Comment by arnaudgiuliani** [comment] 2021-03-05 07:32
StateViewModel API has been restored in 3.0.1, with consistent factory resolution.

**Closed by arnaudgiuliani** 2021-03-05 07:32 UTC
Labels: android, documentation, status:check, type:issue

**Comment by sagarpatel288** [comment] 2021-05-25 07:13
@arnaudgiuliani How do we do that in `2.2.3` with `by inject()`?

**Comment by arnaudgiuliani** [comment] 2021-05-25 07:57
@sagarpatel288 no, just use `by viewModel( state = <Your bundle>)`

**Comment by sagarpatel288** [comment] 2021-05-25 10:28
@arnaudgiuliani Thanks for the quick reply. It says `unresolved reference` for `by viewModel`.

Here are the details:

**Classpath**

```
def koin_version = "2.2.3"
        classpath "io.insert-koin:koin-gradle-plugin:$koin_version"
```

**Plugin**

```
apply plugin: 'koin'
```

**Dependencies**

```

    //Koin
    def koin_version = "2.2.3"

    // Koin Core
    // Koin for Kotlin
   implementation "io.insert-koin:koin-core:$koin_version"
    // Koin extended & experimental features
    implementation "io.insert-koin:koin-core-ext:$koin_version"

    // Koin AndroidX Scope features
    implementation "io.insert-koin:koin-androidx-scope:$koin_version"
    // Koin AndroidX ViewModel features
    implementation "io.insert-koin:koin-androidx-viewmodel:$koin_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.0"
    // Koin AndroidX Fragment features
    implementation "io.insert-koin:koin-androidx-fragment:$koin_version"
    // Koin AndroidX WorkManager
    implementation "io.insert-koin:koin-androidx-workmanager:$koin_version"
    // Koin AndroidX Experimental features
    implementation "io.insert-koin:koin-androidx-ext:$koin_version"
 
    // Koin for Ktor Kotlin
    implementation "io.insert-koin:koin-ktor:$koin_version"
```

**Module**

```
@OptIn(KoinApiExtension::class)
val viewModelModules = module {
    viewModel {
        MeetingViewModel(get())
    }

    factory {
        emptyState()
    }
}
```

**ViewModel**

```
@KoinApiExtension
class MeetingViewModel(val savedStateHandle: SavedStateHandle) : ViewModel() {
```

**Service class**

```
@KoinApiExtension
class ChimeService : LifecycleService()
```

**Usage in the service class**

```
 val meetingViewModel: MeetingViewModel by viewModel( state = emptyState())
```

**Confirmed the Import statement in the service class**
import org.koin.androidx.viewmodel.ext.android.viewModel

**Comment by sagarpatel288** [comment] 2021-05-25 12:23
The current solution is inspired from here:

https://insert-koin.io/docs/reference/koin-core/injection-parameters/

**Module**

```
@OptIn(KoinApiExtension::class)
val viewModelModules = module {
    viewModel {
            (savedStateHandle: SavedStateHandle) -> MeetingViewModel(savedStateHandle)
    }
}
```

**Usage in the service class**

```
val meetingViewModel: MeetingViewModel by inject { parametersOf(SavedStateHandle())}
```

_I hope I am using it properly. Looking for a better way though._

**Comment by arnaudgiuliani** [comment] 2021-05-25 12:25
The usage is not good. It should be `val meetingViewModel: MeetingViewModel by viewModel(state = <YourBundle>)`

**Comment by sagarpatel288** [comment] 2021-05-25 12:31
Yeah... How can I solve "unresolved reference" while trying to use `by viewModel` there? What am I missing here?

**Comment by arnaudgiuliani** [comment] 2021-05-25 13:09
if you gradle config is good, be sure to make the import for extension function.

**Comment by sagarpatel288** [comment] 2021-05-25 13:18
Below import is there but it is not being used even when I use `by viewModel`

```
import org.koin.androidx.viewmodel.ext.android.viewModel
```

**Comment by SameerShelarr** [comment] 2022-08-01 12:53
I m facing this issue while injecting a ViewModel having **SavedStateHandle** as one of the constructor parameter.


Setup:
```
class SampleApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        startKoin {
            printLogger()
            androidContext(this@SampleApplication)
            modules(appModule)
        }
    }
}
```

Module:
```
val appModule = module {

    factoryOf(::SampleUseCase)

    viewModelOf(::SampleViewModel)
}
```

Composable:
```
@Composable
fun SampleComposable(
    navController: NavController,
    viewModel: SampleViewModel = get(),
)
```

ViewModel:
```
class SampleViewModel constructor(
    savedStateHandle: SavedStateHandle,
    private val sampleUseCase: SampleUseCase,
) : ViewModel()
```

I m using `koin_version = '3.2.0'`, `kotlin_version='1.7.0'`, `compose_version = '1.2.0'`

Dependencies in build.gradle:
```
// Koin DI
implementation "io.insert-koin:koin-core:$koin_version"
implementation "io.insert-koin:koin-test:$koin_version"
implementation "io.insert-koin:koin-android:$koin_version"
implementation "io.insert-koin:koin-androidx-compose:$koin_version"
```

**Comment by hakobvardanyan** [comment] 2022-08-05 07:05
@SameerShelarr I have downgraded the koin_version to `3.1.5` and it worked for me. I assume this is a bug in the `3.2.0` version.

**Comment by kassim** [comment] 2024-05-03 09:09
Hi. I'm seeing this same issue reported in `io.insert-koin:koin-android:3.4.3` – its not a consistent issue that we can recreated but it's being reported via Google Play console
