### ISSUE TITLE
Rarely a parametersOf not working

### ISSUE THREAD

**Issue by naixx** [InsertKoinIO/koin#1630] opened 2023-08-02 19:22 UTC
**Describe the bug**
I have a weird crash that happened once on a tester's device.  I got a crash with message `No definition found for class:'ShadowsocksVpnProvider' q:''. Check your definitions!` but this works every other time. This initialisation ran hundreds of times before.

**To Reproduce**
```
App.kt:
   module {
            viewModelOf(::TunnelViewModel)
   }
Activity.kt:
      val tunnelViewModel: TunnelViewModel by viewModel { parametersOf(ShadowsocksVpnProvider(shadowsocksServiceConnection)) }
    private val shadowsocksServiceConnection by lazy { ShadowsocksServiceConnection() }
```
Basically this part initialization works all the time, except when a user opened an app and got a crash

**Koin project used and used version (please complete the following information):**
koin-android 3.4.0

**Comment by arnaudgiuliani** [comment] 2023-08-04 14:17
hard to see, yes 🤔 If you have any way to reproduce 👍

**Comment by naixx** [comment] 2023-08-07 11:30
@arnaudgiuliani that's the problem. If I could reproduce that would be much easier to report. For now I can provide only a stacktrace from one device (the build is not in production, so no stats at all yet)

**Comment by gerbiljames** [comment] 2023-08-15 11:02
This is being caused by parameter resolution not being threadsafe, and is fixed by this [PR](https://github.com/InsertKoinIO/koin/pull/1561). It's more likely to happen when multiple objects are created simultaneously which have dynamic parameters that need to be resolved by Koin.

**Comment by naixx** [comment] 2023-08-28 08:27
@gerbiljames @arnaudgiuliani any chance for the PR to be merged?

**Comment by arnaudgiuliani** [comment] 2023-08-29 13:56
looking at it 👍

**Comment by arnaudgiuliani** [comment] 2023-09-04 10:40
let's see with koin-android 3.5.0 and parameter race condition fix https://github.com/InsertKoinIO/koin/pull/1561 how it goes :+

**Closed by arnaudgiuliani** 2023-09-04 10:40 UTC
Labels: android, type:issue, status:checking
