### ISSUE TITLE
java.util.NoSuchElementException when calling getOrNull() while creating an instance of an injected class with parameters

### ISSUE THREAD

**Issue by jakobulbrich** [InsertKoinIO/koin#1149] opened 2021-07-13 14:10 UTC
**Describe the bug**
Koin crashes with the following exception when resolving an instance with parameters that has a dependant call to `getOrNull()` (which gets not provided) to create the instance.
```
java.util.NoSuchElementException: ArrayDeque is empty.
    at kotlin.collections.ArrayDeque.removeFirst(ArrayDeque.kt:145)
    at org.koin.core.scope.Scope.resolveInstance(Scope.kt:213)
```

**To Reproduce**
1. Create a definition that
**(a)** gets parameters from `parametersOf()`
**(b)** requires a call to `getOrNull()` to create the instance for this definition
```kotlin
factory { params ->
    MyClass(
        name = params.get(),
        optionalInjectedParameter = getOrNull()
    )
}
```
2. Do **not** provide a definition for the parameter that should be resolved via `getOrNull()`
3. Inject it somewhere
```kotlin
val myInjectedClass = get<MyClass> {
    parametersOf("Some parameter")
}
```

**Whats the problem**
* Koin calls `Scope.resolveInstance()` for `MyClass` and puts the parameters on the `_parameterStack`. It then calls `Scope.resolveValue()` to create an instance of `MyClass`.
* While creating the instance Koin does a call to `getOrNull()` as we defined it to provide the optional parameter if it is available. It calls `Scope.resolveValue()` again for the optional parameter and ends up calling `_parameterStack.clear()` and `throwDefinitionNotFound()` from there. The exception is caught within getOrNull() so it gracefully returns `null` for the optional parameter from there and the instance of `MyClass` gets created correctly in `Scope.resolveInstance()`.
* But afterwards it tries to remove the parameters of `MyClass` with `_parameterStack.removeFirst()`. And since the stack was already cleared from within the `getOrNull()` call it crashes here.

**Expected behavior**
Koin should create the instance correctly and should not fail due to intentional optional parameters.
Please note that it can also be the case that we need to call `getOrNull()` from the init block of the injected class for some reasons and not only provide it as a constructor parameter.

**Koin project used and used version (please complete the following information):**
`koin-core version 3.1.2`

**Comment by PaulinaSadowskaAllegro** [comment] 2021-09-06 15:15
Hi! Is there any update about this issue? I have the same problem 😞 
I reproduced the same bug when using `getOrNull()` and I also was able to reproduce this crash using `get()` when dependency was created using multiple scopes (when some dependency is not found in the first scope but in some linked scope,  parameters stack is also cleaned which causes crash later on)

I was able to work around it but I'm afraid it has a potential to 🔥   later on unexpectedly since it's a rather subtle bug 

**Koin project used and used version:** `Koin core version 3.1.1`

**Comment by jairrab** [comment] 2021-10-01 00:53
Hi all, also started seeing this issue the first time when we migrated from `3.0.2` to `3.1.2`

**Comment by imcloud** [comment] 2021-10-21 09:31
I have the same problem. After the release, many users reported this exception, but I can't reproduce it myself

**Comment by Martori** [comment] 2021-11-02 11:47
We are having the same issue. Crashlytics is reporting a crash:
```
Caused by java.util.NoSuchElementException
ArrayDeque is empty.
    kotlin.collections.ArrayDeque.removeFirst (ArrayDeque.kt:145)
    org.koin.core.scope.Scope.resolveInstance (Scope.kt:213)
    org.koin.core.scope.Scope.get (Scope.kt:193)
    org.koin.androidx.viewmodel.factory.DefaultViewModelFactory.create (DefaultViewModelFactory.kt:11)
```
But no one in our team is able to reproduce it.

**Comment by arnaudgiuliani** [comment] 2021-11-02 13:40
Ok, let see what's going on :/ we need to reproduce the problem.

**Comment by smax48** [comment] 2021-11-04 03:43
We experience the same problem, it manifests when there's a reflection-based declaration: `single<SomeType>()`, where `SomeType` constructor is dependent on another instance that is acquired using `getOrNull()` call...

**Comment by arnaudgiuliani** [comment] 2021-11-04 11:33
@smax48 yes, in that case the default way of resolving is the `get()`

**Comment by arnaudgiuliani** [comment] 2021-11-04 11:33
let me investigate on this optional param resolution problem

**Comment by AlexeyGodyaev** [comment] 2021-11-05 20:14
How often does the error occur?

**Comment by arnaudgiuliani** [comment] 2021-11-09 09:00
Fixed in 3.1.4 - 43574dcae258627849a76e1832b8095ce35a4560

**Closed by arnaudgiuliani** 2021-11-09 09:00 UTC
Labels: type:issue, status:accepted, important

**Comment by imcloud** [comment] 2021-12-27 08:24
> Fixed in 3.1.4 - [43574dc](https://github.com/InsertKoinIO/koin/commit/43574dcae258627849a76e1832b8095ce35a4560)

For some reason, our old project cannot upgrad target version or compile version to 29 or above, 
My koin version is 3.1.2, how can I fix this

**Comment by nicolargh** [comment] 2022-03-06 23:36
I've just run into this issue on Koin 3.1.5. I'm honestly at a loss as to how `removeFirstOrNull` can throw a `NoSuchElementException`. I've gotten about ~30 crashes in the last week since upgrading from 2.1.6

Fatal Exception: java.util.NoSuchElementException
ArrayDeque is empty.
kotlin.collections.ArrayDeque.removeFirst (ArrayDeque.kt:145)
kotlin.collections.ArrayDeque.removeFirstOrNull (ArrayDeque.java:157)
org.koin.core.scope.Scope.resolveInstance (Scope.kt:244)
org.koin.core.scope.Scope.get (Scope.kt:204)
org.koin.core.scope.Scope.getOrNull (Scope.kt:172)

**Comment by arnaudgiuliani** [comment] 2022-03-18 10:07
can you reopen a new ticket and provide a quick example to test?

**Comment by nicolargh** [comment] 2022-03-24 04:28
Unfortunately I wasn't able to reproduce this myself, all I have is crash reports. I posted here hoping someone else has seen the same thing and could provide more information.

**Comment by arnaudgiuliani** [comment] 2022-03-24 08:11
are you sure you run with Koin 3.1.5. Else it can be interesting to check your Kotlin version behind that.

**Comment by npresseault** [comment] 2022-11-02 17:02
This bug is still present in latest releases with `removeFirstOrNull`. This happens when we use koin to get the instance of an injected class across with parameters across multiple threads. In our case, the creation of this instance was done using Dispatchers.default which is backed by a thread pool.

This is a race condition hence why it is hard to reproduce but I bet that it could be done in a small project doing multithreading.
