### ISSUE TITLE
SavedStateHandle is not resolved when using R8

### ISSUE THREAD

**Issue by Nek-12** [InsertKoinIO/koin#1468] opened 2022-11-09 11:51 UTC
When using SavedStateHandle starting with 3.2.2, injecting SavedStateHandle crashes the app.

Specifically, the function named `needSavedStateHandle()` which retrieves it using class name which will be erased.

**To Reproduce**
1. Enable R8 in the project with default configuration
2. Inject SavedStateHandle into a viewmodel
3. App crashes with `NoBeanDefinitionException`

**Expected behavior**
SavedStateHandle is injected

**Koin project used and used version (please complete the following information):**
3.2.2

Temporary fix:
Add `SavedStateHandle` to keep rules.

**Comment by sudansh** [comment] 2022-11-10 08:36
Can reproduce the error with 3.3.0 version also.

**Comment by StylianosGakis** [comment] 2022-11-28 23:18
I was also getting not being able to resolve a class which after obfuscation was named "androidx.lifecycle.s0" which lead me to believe it was androidx.lifecycle.ViewModel, but no, androidx.lifecycle.SavedStateHandle also is on the same package.

Is this due to [this line](https://github.com/InsertKoinIO/koin/blob/d2a38bb66268e2cda75fb3c262796a5881bcddbd/android/koin-android/src/main/java/org/koin/androidx/viewmodel/GetViewModel.kt#L73-L77) maybe, since we're looking for the name, but that name isn't there after obfuscation? Or is it something else?

**Comment by StylianosGakis** [comment] 2022-11-28 23:26
For anyone who may be looking for how to add this to the proguard rules, this worked for me.
`-keepnames class androidx.lifecycle.SavedStateHandle`
If it's wrong in some way please do let me know 😊

**Comment by Nek-12** [comment] 2022-12-03 11:37
So what will be the solution for this?
The simplest one would to just include the keep rule into consumer-rules.pro of the library. However I'd really like to avoid such thing

**Comment by arnaudgiuliani** [comment] 2022-12-13 10:15
Fixed in 3.3.1

**Closed** 2022-12-13 10:15 UTC
Labels: android, type:issue, status:checking
