### ISSUE TITLE
Recreated scope provides the same instance for scoped component

### ISSUE THREAD

**Issue by yarkh** [InsertKoinIO/koin#366] opened 2019-02-15 14:14 UTC
I want to get new scoped instances after scope recreation, even for the same scope id.
Sample code:
```
scope(SCOPE_NAME) {
    scoped { ComponentA() }
}
```
```
val scope1 = getKoin().createScope(scopeId, SCOPE_NAME)
val comp1 = scope.get<ComponentA>()
scope1.close()

val scope2 = getKoin().createScope(scopeId, SCOPE_NAME)
val comp2 = scope.get<ComponentA>()
```

Expected comp1 != comp2 as scope2 was created from scratch, but it is the same instance.

koin-core version 2.0.0-beta-1

**Comment by erickok** [comment] 2019-02-15 14:36
Think this is a duplicate of #354

**Comment by yarkh** [comment] 2019-02-15 15:33
Looks like bug in ScopeDefinition release method
```
internal fun release(instance: ScopeInstance) {
    definitions.filter { it is ScopedInstance<*> }.forEach { it.instance.release(InstanceContext(scope = instance)) }
}
```
Should be:
```
internal fun release(instance: ScopeInstance) {
    definitions.filter { it.instance is ScopedInstance<*> }.forEach { it.instance.release(InstanceContext(scope = instance)) }
}
```

**Closed** 2019-02-22 15:33 UTC
Labels: status:duplicated

**Comment by feresr** [comment] 2019-03-01 14:07
Hi, I'm still having this issue:


```
abstract class BaseActivity<S : State> : AppCompatActivity() {

    abstract val viewModel: BaseViewModel<S>
    protected val activityScope = getKoin().getOrCreateScope(this::class.getFullName())

    abstract fun onStateChanged(state: S)

    final override fun onStart() {
        super.onStart()
        viewModel.register(::onStateChanged)
        onStartInternal()
    }

    final override fun onStop() {
        onStopInternal()
        viewModel.unregister()
        super.onStop()
    }

    override fun onDestroy() {
        if (!isChangingConfigurations) {
            viewModel.onCleared()
            activityScope.close()
        }
        super.onDestroy()
    }

    protected open fun onStartInternal() {}
    protected open fun onStopInternal() {}
}
```


```
class MainActivity : BaseActivity<HomeState>() {

    override val viewModel: MainViewModel by activityScope.inject { parametersOf(this) }

```

Launching this activity again will provide the same `MainViewModel` instance
