### ISSUE TITLE
ScopeDSL.viewModel is returning singleton instance of all view models

### ISSUE THREAD

**Issue by crocsandcoffee** [InsertKoinIO/koin#1240] opened 2021-12-03 19:50 UTC
**Describe the bug**

ScopeDSL.viewModel is returning singleton instance of all view models 

See the code snippet below  for reference: 

```
inline fun <reified T : ViewModel> ScopeDSL.viewModel(
    qualifier: Qualifier? = null,
    noinline definition: Definition<T>
): Pair<Module, InstanceFactory<T>> {
    return scoped(qualifier, definition)
}
```

`return scoped(qualifier, definition)` is wrong and should be replace with `return factory(qualifier, definition)`

**Expected behavior**
A new instance of the view model should be returned instead of a singleton instance (unless this is a shared view model instance on Activity that is being injected into Fragment)

**Koin project used and used version (please complete the following information):**
v3.1.4

**Comment by arnaudgiuliani** [comment] 2021-12-07 10:11
Hello @crocsandcoffee 

it's not an error here, as the scoped VM instance is regenerated from the ViewModelFactory. It can then survive to Activity.

**Comment by crocsandcoffee** [comment] 2021-12-07 13:57
> Hello @crocsandcoffee 
> 
> it's not an error here, as the scoped VM instance is regenerated from the ViewModelFactory. It can then survive to Activity.

Here's what happens, I'm in Activity A and I launch Activity B, which has this scoped view model injected. I call Activity B finish() and return to Activity A. I start Activity B again, and the _same scoped view model instance_ is injected, it should be a new view model instance when a new activity is created. @arnaudgiuliani

**Comment by thadcodes** [comment] 2021-12-07 15:58
@arnaudgiuliani I created an example app that shows the issue here: https://gist.github.com/thadcodes/0c0cc293be80ddff38ebe76f12f68fe3

It allows you to specify a scope ID and text to show on the next screen.  You will notice that if you change the text field for a second call without changing the scope ID it returns the old text instead of one from a new view model even though I'm calling a new activity with new parameters and would expect it to create a new view model.  If you change the scope ID to create a new scope it then changes it.  This makes it impossible to use with a scope that spans multiple activities. 

I can provide example uses if you are still not convinced it's a bug

**Comment by thadcodes** [comment] 2021-12-09 13:49
> @arnaudgiuliani I created an example app that shows the issue here: https://gist.github.com/thadcodes/0c0cc293be80ddff38ebe76f12f68fe3
> 
> It allows you to specify a scope ID and text to show on the next screen. You will notice that if you change the text field for a second call without changing the scope ID it returns the old text instead of one from a new view model even though I'm calling a new activity with new parameters and would expect it to create a new view model. If you change the scope ID to create a new scope it then changes it. This makes it impossible to use with a scope that spans multiple activities.
> 
> I can provide example uses if you are still not convinced it's a bug

BTW I can also provide a zip to an entire project that reproduces this on slack if need be.   Let me know if you want it and I'll send it to you on kotlin slack

**Comment by arnaudgiuliani** [comment] 2021-12-09 16:09
>I'm AFK right now, but I believe scoped(qualifier, definition) returns a Singleton instance of the view model, and injects that same instance into any component that asks for this scoped view model.

is your Activity really destroyed? I need to investigate then. You can help by providing a sample project if you can.

**Comment by thadcodes** [comment] 2021-12-09 16:33
> > I'm AFK right now, but I believe scoped(qualifier, definition) returns a Singleton instance of the view model, and injects that same instance into any component that asks for this scoped view model.
> 
> is your Activity really destroyed? I need to investigate then. You can help by providing a sample project if you can.

@arnaudgiuliani I sent you a message in kotlin slack with an example project

**Comment by arnaudgiuliani** [comment] 2021-12-09 16:37
ok great, thanks.

**Comment by arnaudgiuliani** [comment] 2021-12-14 08:34
If you want your Scope to follow the Android Lifecycle, use the Android Scope API: https://insert-koin.io/docs/reference/koin-android/scope#use-an-android-scope

either use the `ActivityScope` class to replace your `Activity`, either use your `AndroidScopeComponent` interface with `activityScope()` delegate.

A `scoped` definition is kept until the scope is dropped. If you are controlling it manually (not tied to the Android lifecycle), you need to close the scope when you're done.

**Comment by arnaudgiuliani** [comment] 2021-12-14 08:35
@thadcodes in your case, you create manually a scope and never close it.

**Comment by StanislavChumarin** [comment] 2021-12-16 13:37
@arnaudgiuliani  but why did you do that? ViewModels are controlled by Activity/Fragment and catching instances breaks that contract.
If I want to make 
```
scope(USER_SCOPE_QUALIFIER) {
   viewModel { UserDataViewModel(get<UserKey>()) }
} 
```

Later in Fragment 
`val vModel:UserDataViewModel by getUserScope().viewModel()`

Since 3.1.3
This UserDataViewModel is "singleton" now. And re-enter that fragment gets cleared! view model, so no `launch{}` will work.

**Comment by thadcodes** [comment] 2021-12-16 13:41
> @arnaudgiuliani but why did you do that? ViewModels are controlled by Activity/Fragment and catching instances breaks that contract. If I want to make
> 
> ```
> scope(USER_SCOPE_QUALIFIER) {
>    viewModel { UserDataViewModel(get<UserKey>()) }
> } 
> ```
> 
> Later in Fragment `val vModel:UserDataViewModel by getUserScope().viewModel()`
> 
> Since 3.1.3 This UserDataViewModel is "singleton" now. And re-enter that fragment gets cleared! view model, so no `launch{}` will work.

@StanislavChumarin as a work around for now you can change your code above to the below:

```kotlin
scope(USER_SCOPE_QUALIFIER) {
   factory { UserDataViewModel(get<UserKey>()) }
} 
```

`viewModel` declaration is really just an alias anyway.  My team actually created our own function to do this 
```kotlin
inline fun <reified T : ViewModel> ScopeDSL.scopedViewModel(
    qualifier: Qualifier? = null,
    noinline definition: Definition<T>
): Pair<Module, InstanceFactory<T>> {
    return factory(qualifier, definition)
}
```

to use it we just call `scopedViewModel` instead of `viewModel` to declare it

**Closed** 2021-12-16 20:29 UTC
Labels: android, type:issue, important
