### ISSUE TITLE
Crash in Koin 3.1.3: "SavedStateProvider with the given key is already registered"

### ISSUE THREAD

**Issue by andersu** [InsertKoinIO/koin#1207] opened 2021-11-05 08:59 UTC
**Describe the bug**
When upgrading from Koin 3.1.2 to 3.1.3 we started getting some crashes in our app.
We do not know for sure if Koin is at fault, but the stack trace implies it:
```
Fatal Exception: java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
       at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
       at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
       at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:70)
       at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:169)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:139)
       at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolverKt.java:15)
       at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExtKt.java:65)
       at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExtKt.java:52)
       at org.koin.androidx.viewmodel.ext.android.ComponentCallbackExtKt.getViewModel(ComponentCallbackExtKt.java:61)
       at org.koin.androidx.viewmodel.ext.android.ComponentCallbackExtKt.getViewModel$default(ComponentCallbackExtKt.java:54)
       at org.koin.androidx.viewmodel.ext.android.ComponentCallbackExtKt.getViewModel$default(ComponentCallbackExtKt.java:50)
       at com.action.consumerapp.feature.search.ProductSearchFragment$special$$inlined$viewModel$default$1.invoke(ProductSearchFragment.java:63)
       at com.action.consumerapp.feature.search.ProductSearchFragment$special$$inlined$viewModel$default$1.invoke(ProductSearchFragment.java:41)
       at kotlin.UnsafeLazyImpl.getValue(UnsafeLazyImpl.java:81)
       at com.action.consumerapp.feature.search.ProductSearchFragment.getViewModel(ProductSearchFragment.java:52)
       at com.action.consumerapp.feature.search.ProductSearchFragment.onDestroy(ProductSearchFragment.java:100)
       at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3217)
       at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:756)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:333)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1788)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1721)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1658)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7604)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**To Reproduce**
Unfortunately, we have not been able to reproduce the issue ourselves.

**Expected behavior**
The app should not crash.

**Koin project used and used version (please complete the following information):**
`io.insert-koin:koin-android:3.1.3`

**Additional moduleDefinition**
We use `viewModel {` in our module and `by viewModel()` in our fragments/activities.
Could this change from the changelog be related?
_"[DEPRECATED] [android] - by stateViewModel() is deprecated. state parameter is not needed anymore. It's now merged into viewModel(), to inject SavedStateHandle"_

**Comment by arnaudgiuliani** [comment] 2021-11-12 07:35
Do you try to use another ViewModel instance of the same type? (different scope or something)

**Comment by victorlapin** [comment] 2021-11-16 08:57
Maybe I can be of some help, as I've solved a similar issue recently. 

I've encountered this one with a scoped ViewModel, and the problem was in incorrectly set owner. In my case, I've set the owner manually to requireParentFragment(), which was the main NavHostFragment of the app. I guess, that prevented the ViewModel instance from being killed with the scope, so it crashed on consequent injections with the same ViewModel class and owner.

Ian Lake from Google suggested to use NavBackStackEntry as a ViewModel owner, and that was indeed the fix for my case. Hope it helps somehow.

**Comment by sebastinto** [comment] 2021-11-17 18:07
A similar error happens **on configuration changes** (rotation) for me, after upgrading to 3.1.3 from 3.1.2.

In module: `viewModel { MyViewModel(get(), get(), get(), get(), get()) }`
In fragment class:  `by sharedViewModel()`

The error:
`Unable to destroy activity {foo.bar.ui.activities.MainActivity}: java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered`

**Comment by arnaudgiuliani** [comment] 2021-11-18 13:35
Can anyone help with a project reproducing it? I believe there is a similar problem with Hilt. It can comes from underlying ViewModel library.

**Comment by sebastinto** [comment] 2021-11-20 18:18
Haven't been able to replicate by wiring up a simple project. Not sure where the problem is. Unfortunately I cannot share the project where I encountered the issue. Will continue trying.

**Comment by arnaudgiuliani** [comment] 2021-11-22 16:59
ok. I believe there is constraints under the hood. Let's with new android/ktx lib update. I've seen same kind of issue in Hilt.

**Comment by NickButcher1** [comment] 2021-11-29 10:08
I also see the `java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered` error after upgrading from Koin 3.1.2 to 3.1.3 or 3.1.4.

I can't provide a sample project (I see this in a large codebase where it would take me a long time to extract something I can share).  But I'm happy to provide any more information I can to help.

**Comment by arnaudgiuliani** [comment] 2021-11-29 16:47
If someone can help reproduce it, would be great 👍

**Comment by jhascoet** [comment] 2021-12-10 08:11
Hi there
Any news regarding that opened issue ?

**Comment by damianogiusti** [comment] 2021-12-10 13:36
Hi @arnaudgiuliani , I also experienced this issue. I'm sorry I'm not able to provide you a sample project to replicate the issue right now. However, if I got it right, these should be the steps that you need to follow to reproduce the issue.

Using Koin 3.1.4:

- Parent fragment and child fragment that share the same ViewModel (i.e. a simple fragment with a bottom sheet shown using the child fragment manager)
- The parent uses `this` as `owner` when calling the `sharedViewModel()` delegate, while the child uses `parentFragment` as `owner`;
- Starting from the parent fragment, navigate out in order to destroy the parent fragment. Then, navigate back to such fragment.

You should get this exception:

```stacktrace
2021-12-10 09:31:46.657 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <redacted>, PID: 31487
    java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
        at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
        at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:70)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:15)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:67)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:53)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel$default(ScopeExt.kt:45)
        at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getSharedViewModel(FragmentExt.kt:59)
        at <redacted>.RealtimeFragment$special$$inlined$sharedViewModel$default$2.invoke(FragmentExt.kt:61)
        at <redacted>.RealtimeFragment$special$$inlined$sharedViewModel$default$2.invoke(FragmentExt.kt:39)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at <redacted>.RealtimeFragment.getVm(RealtimeFragment.kt:43)
        at <redacted>.RealtimeFragment.setupRecyclerView(RealtimeFragment.kt:197)
```

**Comment by afaktor** [comment] 2022-01-10 15:49
This issue is still happening in 3.1.5. 
We recently upgraded from Koin 2 to Koin 3 and the app is crashing on  `by sharedViewModel()` call.

`    java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
        at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
        at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:70)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:169)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:15)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:67)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:53)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel$default(ScopeExt.kt:45)
        at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getSharedViewModel(FragmentExt.kt:59)
        at com.x.xx.xxx.managedprofile.ManagedProfileIntroFragment$special$$inlined$sharedViewModel$default$2.invoke(FragmentExt.kt:61)
        at com.x.xx.xxx.managedprofile.ManagedProfileIntroFragment$special$$inlined$sharedViewModel$default$2.invoke(FragmentExt.kt:39)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.oneabbott.restore.consumer.managedprofile.ManagedProfileIntroFragment.getManagedProfileViewModel(ManagedProfileIntroFragment.kt:19)
        at com.x.xx.xxx.managedprofile.ManagedProfileIntroFragment.onCreateView(ManagedProfileIntroFragment.kt:36)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by arnaudgiuliani** [comment] 2022-01-11 14:22
Are you using the shared ViewModel elsewhere?

**Comment by afaktor** [comment] 2022-01-13 13:06
Yes I'm pretty extensively in the app.  Apologies for the noise, I've cleaned, and rebuilt the emulator and am no longer seeing the crash. Please feel free to close the issue.

**Comment by AnandaDwiprayoga** [comment] 2022-01-14 04:24
Got some issues too when using sharedViewModel

**Comment by AntonZubchenok** [comment] 2022-01-19 19:19
It is reproduced in 3.1.5 version. Are you going to fix it somehow?

`private val viewModel by sharedViewModel<BaseWalletViewModel>() { parametersOf(requireActivity()) }`

`    viewModel<BaseWalletViewModel> { (activity: Activity) ->
        WalletViewModel(get(), get(),...)
    }`

```    java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
        at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
        at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:70)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:15)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:67)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:53)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel$default(ScopeExt.kt:45)
        at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getSharedViewModel(FragmentExt.kt:59)
        at com.b9.app.features.screens.wallet.WalletScreen$special$$inlined$sharedViewModel$default$2.invoke(FragmentExt.kt:61)
        at com.b9.app.features.screens.wallet.WalletScreen$special$$inlined$sharedViewModel$default$2.invoke(FragmentExt.kt:39)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.b9.app.features.screens.wallet.WalletScreen.getViewModel(WalletScreen.kt:46)
        at com.b9.app.features.screens.wallet.WalletScreen.onViewCreated(WalletScreen.kt:57)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2967)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:529)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1785)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1709)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1646)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:480)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by tomtaila** [comment] 2022-01-21 23:32
I have the same issue (working within an NDA so I can't share my code but here are the steps to reproduce):

```
// module
    viewModel {
        ScreenSettingsVM(
            app = androidApplication()
        )
    }
```

```
@Composable
fun ScreenSettings(modifier: Modifier = Modifier, navController: NavHostController) {
    val vm = getViewModel<ScreenSettingsVM>()
    .
    .
}
```
 Steps are:
 - Go to settings screen above
 - Open an external email app via an intent
 - Navigate back to app via system back
 - Leave settings screen 
 - Re-enter settings screen
 - Crash
 
 
 ```
     // Koin main features for Android (Scope,ViewModel ...)
    implementation "io.insert-koin:koin-android:3.1.5"
    // Koin Java Compatibility
    implementation "io.insert-koin:koin-android-compat:3.1.5"
```

**Comment by tomtaila** [comment] 2022-01-26 20:02
Hey I'm getting this more and more frequently - What's going on here? Is there a work around for now?

I am not using a sharedviewmodel just a normal viewmodel and it seems to happen randomly. Please help since this is big issue

**Comment by anupgeorge1979** [comment] 2022-02-10 22:12
Can you enable 'Developer options -> Don't keep activities' and see if its reproduced 100%

**Comment by masztalski** [comment] 2022-02-17 17:18
@anupgeorge1979  I have tried such solution but nothing happened. I'm seeing in my logs this crash quite a lot and I'm worried. All viewModels are injected by koin. Including few sharedViewModels.

**Comment by arnaudgiuliani** [comment] 2022-02-18 07:56
anyone has a sample app to help reproduce directly the case?

**Comment by masztalski** [comment] 2022-02-18 08:00
I have app public available which causes trouble, but as I said - I cannot reproduce it. It happens only on production, but you can try: https://install.appcenter.ms/users/michal.markiewicz-intive.com/apps/zwalkowepegle/distribution_groups/public

**Comment by arnaudgiuliani** [comment] 2022-02-18 08:37
is it a Jetpack Compose app?

**Comment by anonym24** [comment] 2022-02-20 11:37
Wow. It is still not fixed. For my own apps I use Koin. At office work I use Hilt. And now I think to use Hilt everywhere. Quite disappointed

**Comment by corgivn** [comment] 2022-03-07 10:48
> anyone has a sample app to help reproduce directly the case?

hi, @arnaudgiuliani 
I have created a project to help you reproduce this issue.
https://github.com/corgivn/koin-example-issue-shared-viewmodel/tree/main
Pls help to take a look
Many thanks

**Comment by arnaudgiuliani** [comment] 2022-03-18 10:35
Many thanks for your help @corgivn 
Let me take a look 👍

**Comment by arnaudgiuliani** [comment] 2022-03-25 08:09
working on it

**Comment by victorlapin** [comment] 2022-03-25 08:14
> working on it

Were you able to locate the issue?

**Comment by r4phab** [comment] 2022-03-25 09:58
Just to put it here, I found out what was causing the issue in my project. 
I had the same issue mentioned here, then downgrading to 3.1.2 and encountered a crash but this time I got another Koin exception mentioning that I forgot to declare a dependency for my viewModel.
I added the dependency declaration to my module for the app to work with 3.1.2, upgrading to 3.1.5, and now everything works fine .. so maybe the issue is just the printed error message ?

**Comment by arnaudgiuliani** [comment] 2022-03-25 10:29
Locating some stuff. Need a bit of investigation to help and be sure I can sort out a consistent solution

**Closed** 2022-04-06 07:03 UTC
Labels: android, type:issue, status:accepted, important

**Comment by arnaudgiuliani** [comment] 2022-04-06 07:04
Fixed 🎉 - The Google's ViewModel API pushed to resolve factory regarding the main thread, provoking the "SavedStateProvider with the given key is already registered" error.

It should be ok for 3.1.6

**Comment by victorlapin** [comment] 2022-04-06 07:23
Should we also expect the fix in 3.2.0-beta-2?

**Comment by arnaudgiuliani** [comment] 2022-04-06 07:28
yes, fixes in 3.1.6 will be merged in 3.2.0

**Comment by andersu** [comment] 2022-05-04 06:46
After staying safe on 3.1.2 for a while, we upgraded to 3.1.6 when seeing this issue was fixed.
But our crash reporting tool shows that it started happening again to multiple users.

I have not been able to reproduce it myself yet.

```
Fatal Exception: java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
       at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
       at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
       at androidx.lifecycle.SavedStateHandleController.attachHandleIfNeeded(SavedStateHandleController.java:101)
       at androidx.lifecycle.AbstractSavedStateViewModelFactory.onRequery(AbstractSavedStateViewModelFactory.java:103)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:160)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:139)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:44)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:31)
       at com.action.consumerapp.feature.search.ProductSearchFragment.getViewModel(ProductSearchFragment.kt:53)
       at com.action.consumerapp.feature.search.ProductSearchFragment.onDestroy(ProductSearchFragment.kt:101)
       at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3251)
       at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:780)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:335)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by arnaudgiuliani** [comment] 2022-05-04 12:56
Koin 3.2 reintroduces the default factory which avoids using `AbstractSavedStateViewModelFactory`. This will solve some of the problems hopefully.

**Comment by fandrade-it** [comment] 2022-05-09 15:40
I updated to '3.2.0-beta-1' but still crashing :(

**Comment by gazanfarov** [comment] 2022-08-16 06:27
I'm currently using version 3.1.6 and still get this crashes when using shared view model on screen orientation change
