### ISSUE TITLE
Does not support Kotlin 1.6.0

### ISSUE THREAD

**Issue by Nek-12** [InsertKoinIO/koin#1188] opened 2021-10-21 16:49 UTC
**Describe the bug**
Latest koin version produces` NoSuchMethodError`s at runtime when using kotlin 1.6.0-RC

**To Reproduce**
1. Add latest stable koin dependency
2. Use kotlin 1.6.0-RC.
3. App crashes on startup in 100% cases

**Expected behavior**
The app is able to run without crashing. 

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin version 3.1.2`, kotlin 1.6.0-RC
 
 The surest way to get a runtime error is to call a deleted method toDouble() of kotlin.duration that was removed in 1.6.0 by using 
```
startKoin {
            androidContext(applicationContext)
            androidLogger() //This one is causing the crash
            modules(/* blah */)
        }
```

Stacktrace:
```
java.lang.NoSuchMethodError: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in /data/app/~~RAEJCWfLUZeoA5jJfJMmtA==/com.nek.test.debug-jvqFgZyETecELyVm71SR5A==/base.apk!classes16.dex)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:59)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:50)
        at com.nek.test.TestApplication$onCreate$1.invoke(TestApplication.kt:30)
        at com.nek.test.TestApplication$onCreate$1.invoke(TestApplication.kt:27)
        at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:64)
        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
        at com.nek.test.TestApplication.onCreate(TestApplication.kt:27)
    //bunch of junk    
```

Lesson: do not use experimental APIs

**Comment by franciscofranco** [comment] 2021-11-16 10:28
Hi. Any update on this issue? Kotlin 1.6.0 has been released to production and this crash happens, making it impossible to upgrade Kotlin...
Thanks.

**Comment by SerggioC** [comment] 2021-11-16 11:28
same thing. 
java.lang.NoSuchMethodError: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in /data/app/..
Do I need to trash Koin or downgrade Kotlin?

**Comment by victorlapin** [comment] 2021-11-16 12:50
Set Koin logger to level Error, as a workaround for the time being

**Comment by SerggioC** [comment] 2021-11-16 15:58
> Set Koin logger to level Error, as a workaround for the time being
> 
> ```
>     startKoin {
>         androidLogger(if (BuildConfig.DEBUG) Level.ERROR else Level.NONE)
>         androidContext(context)
>         modules(allModules)
>     }
> ```

That worked. Thanks.

**Comment by arnaudgiuliani** [comment] 2021-11-29 10:01
Yes sorry, use this workaround for now.

**Comment by jemshit** [comment] 2021-12-03 20:22
I remember another bug related to this `androidLogger` before 🧐

**Comment by TreeFrogApps** [comment] 2021-12-04 23:55
> Set Koin logger to level Error, as a workaround for the time being
> 
> ```
>     startKoin {
>         androidLogger(if (BuildConfig.DEBUG) Level.ERROR else Level.NONE)
>         androidContext(context)
>         modules(allModules)
>     }
> ```

For those creating their own `Logger` (for me I created a custom logger wrapping `Timber`) and not using `AndroidLogger` make sure to include you this as the argument to the base `Logger` class.

**Comment by gmk57** [comment] 2021-12-07 16:04
> I remember another bug related to this `androidLogger` before :monocle_face:

Yes, exactly the same happened when Kotlin 1.5 was released: #1076
`Duration` is nice, but we really should think twice before using experimental API in a public library.

**Comment by jiurchuk** [comment] 2021-12-13 00:13
Workaround for Ktor:

```
    install(Koin) {
        slf4jLogger(**level = Level.ERROR**)
        modules(

        )
    }
```

**Comment by EGFireball** [comment] 2021-12-14 08:32
> Set Koin logger to level Error, as a workaround for the time being
> 
> ```
>     startKoin {
>         androidLogger(if (BuildConfig.DEBUG) Level.ERROR else Level.NONE)
>         androidContext(context)
>         modules(allModules)
>     }
> ```

This works ! Thanks !

**Comment by muhrifqii** [comment] 2021-12-18 06:24
my case, also get rid of manually set logger for now

```kotlin
startKoin {
            androidLogger(Level.ERROR)
            //logger(object : Logger() {
            //    override fun log(level: Level, msg: MESSAGE) {
            //        Timber.tag("koin(di)").d(msg)
            //    }
            //})
            //...
}
```

**Comment by cikpis** [comment] 2021-12-27 10:41
Hey guys, any news on this? Using KMM I couldn't find a way to fix this crash. Even creating a `ErrorLogger` did not work for me

```
startKoin {
    logger(ErrorLogger())
    appDeclaration?.invoke(this)
    modules(koinModules)
}

class ErrorLogger : Logger(Level.ERROR) {
    override fun log(level: Level, msg: MESSAGE) {
        println(msg)
    }
}
```
Any help?

**Comment by athulcek** [comment] 2021-12-27 17:07
const val KOIN = "3.1.4"
 const val KOTLIN = "1.6.0"
Crash Log:
 Caused by: o6.c: Could not create instance for [Singleton:'v3.c']
in Release Build

**Comment by TreeFrogApps** [comment] 2021-12-27 23:52
> Hey guys, any news on this?
> 
> Using KMM I couldn't find a way to fix this crash. Even creating an `ErrorLogger` did not work for me.
> 
> ```
> startKoin {
>     logger(ErrorLogger())
>     appDeclaration?.invoke(this)
>     modules(koinModules)
> }
> 
> class ErrorLogger : Logger(Level.ERROR) {
>     override fun log(level: Level, msg: MESSAGE) {
>         println(msg)
>     }
> }
> ```
> 
> Any help?

As `Looger::log(level: Level, msg: MESSAGE)` is abstract need to check the level in your custom logger before blindly logging.

Example : 

`
override fun log(level: Level, msg: MESSAGE) {
            if (level <= this.level) {
                 println(msg)
            }
        }
`

**Comment by lotdrops** [comment] 2022-01-06 13:12
@cikpis I got it working in KMM in two ways:
1) With an expect logger and actual implementations:
Common: `expect val koinLogger: KoinApplication.() -> Unit`  
Android: 
```
actual val koinLogger: KoinApplication.() -> Unit = {
    androidLogger(level = Level.ERROR)
}
```  
iOS: `actual val koinLogger: KoinApplication.() -> Unit = {}`  
Then, in the startKoin block you run `koinLogger()`.

2) Providing platform app declarations to the koin init in shared:
```
internal fun initKoin(appDeclaration: KoinAppDeclaration = {}) =
    startKoin {
        appDeclaration()
        modules(
            // your modules...
        )
    }
```
Also in shared:
```
fun initKoinAndroid(appDeclaration: KoinAppDeclaration = {}) =
    initKoin(appDeclaration)
```
Then in the app module in Android, in MyApplication/BaseApplication:
```
initKoinAndroid() {
            androidLogger(Level.ERROR)
            androidContext(this@MyApplication)
            // optional: modules(appModule)
        }
```

**Comment by cikpis** [comment] 2022-01-10 07:43
Thanks @lotdrops, I'll give it a try and keep you posted.

**Comment by hoc081098** [comment] 2022-01-11 18:17
any release for kotlin 1.6.0?

**Comment by arnaudgiuliani** [comment] 2022-01-12 16:18
Koin 3.2.0 will bring Kotlin 1.6

**Comment by adhirajsinghchauhan** [comment] 2022-01-27 10:18
> Yes, exactly the same happened when Kotlin 1.5 was released: #1076
`Duration` is nice, but we really should think twice before using experimental API in a public library.

Goes back even further; Kotlin 1.4: #847

**Comment by adhirajsinghchauhan** [comment] 2022-01-27 10:46
> Koin 3.2.0 will bring Kotlin 1.6

Great news, but note that anyone who still targets SDK 29 won't be able to update to Koin 3.2.0:
Koin 3.1.3+ updates its `androidx.activity:activity-ktx` dependency to 1.3.1, which requires a minCompileSdk of 30.

Play Store required all app updates to target SDK 30 back in November 2021, but if you're not using it to publish apps, you're stuck with this workaround (suggested earlier in this thread):
```kotlin
startKoin {
    androidLogger(Level.ERROR) // default Level.INFO
    ...
}

**Comment by gmk57** [comment] 2022-01-27 19:02
> anyone who still targets SDK 29 won't be able to update to Koin 3.2.0

What prevents you from having `compileSdk 30` (or 31) and `targetSdk 29` (or even lower)? They are completely different attributes. And despite [old](https://stackoverflow.com/a/49034381) [posts](https://www.reddit.com/r/androiddev/comments/8wxuci/questions_about_3rd_party_libraries_targeting_api/e1zkbx4/) about library's `targetSdk` getting merged into resulting manifest, that doesn't seem to be the case nowadays.

**Comment by arnaudgiuliani** [comment] 2022-02-03 09:18
Koin 3.2 is updated for Kotlin 1.6.10 👍

**Closed by arnaudgiuliani** 2022-02-03 09:18 UTC
Labels: core, important

**Comment by cikpis** [comment] 2022-02-03 14:28
@arnaudgiuliani great news! Do you guys know already when will it be released?

**Comment by JyotimoyKashyap** [comment] 2022-02-18 16:15
> Workaround for Ktor:
> 
> ```
> install(Koin) {
>     slf4jLogger(level = Level.ERROR) //This params are the workaround itself
>     modules(
>         //specify your modules
>     )
> }
> ```

Thanks this works for me.

**Comment by majidebraa** [comment] 2022-02-25 13:40
> Koin 3.2 is updated for Kotlin 1.6.10 👍

3.2.0-beta-1 still does not work for me with Kotlin 1.6.10 and the app gets crash and generates these errors for all module injections:
org.koin.core.error.InstanceCreationException: Could not create an instance for [Factory:
org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:

**Comment by victorlapin** [comment] 2022-02-25 16:31
> > Koin 3.2 is updated for Kotlin 1.6.10 👍
> 
> 3.2.0-beta-1 still does not work for me with Kotlin 1.6.10 and the app gets crash and generates these errors for all module injections: org.koin.core.error.InstanceCreationException: Could not create an instance for [Factory: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:

That's weird, because I've updated to 3.2.0-beta-1 in several different projects, and all worked fine. Maybe check your other artifacts, for example, DBInspector is using Koin as well, and it's linked with 3.1.4 (we've had to temporarily exclude it from our project)

**Comment by AlineCruzDEV** [comment] 2022-08-09 20:38
> 
> ```
>     startKoin {
>         androidLogger(if (BuildConfig.DEBUG) Level.ERROR else Level.NONE)
>         androidContext(context)
>         modules(allModules)
>     }
> ```

This works for me! Thanks!

**Comment by Basitali12** [comment] 2023-05-15 06:42
if any one facing issue like: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in 

so you to  change "androidLogger()" to androidLogger(if (BuildConfig.DEBUG) Level.ERROR else Level.NONE) 
  
  koin = startKoin {
            // Koin Android logger
        
            androidLogger(if (BuildConfig.DEBUG) Level.ERROR else Level.NONE)
            //inject Android context
            androidContext(this)
            modules(modules)
        }
