### ISSUE TITLE
method Fragment.viewModel is not completely lazy. 

### ISSUE THREAD

**Issue by Copatych** [InsertKoinIO/koin#1395] opened 2022-07-28 11:02 UTC
**Bug description**

Previously (koin 3.1.2), when `val viewModel: AbcdeViewModel by viewModel()` was written, all the code was executed lazy.

In the current version (3.2.0), if we look at the source code, we will see that part of the code is executed immediately:
```
@OptIn(KoinInternalApi::class)
inline fun <reified T : ViewModel> Fragment.viewModel(
    qualifier: Qualifier? = null,
    noinline owner: ViewModelStoreOwnerProducer = { this },
    noinline parameters: ParametersDefinition? = null
): Lazy<T> {
    val scope = getKoinScope()
    return viewModels(ownerProducer = owner) {
        getViewModelFactory<T>(owner(), qualifier, parameters, scope = scope)
    }
}
```

`val scope = getKoinScope()` will be called immediately. 

There is a project in which each fragment implements the KoinComponent interface as follows
```
override fun getKoin(): Koin {
    return if (parentFragment is KoinComponent) (parentFragment as KoinComponent).getKoin() else GlobalContext.get()
}
```
In the fragment constructor, when `val ViewModel: AbcdeViewModel by ViewModel()` is called, the fragment does not have a parent yet. And `by viewModel` is always called using GlobalContext

**Expected behavior**
All code in Fragment.viewModel method is executed lazy.

**Used koin version:**
koin 3.2.0

**Workaround**

Something like this
```
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModel
import org.koin.androidx.viewmodel.ext.android.getViewModel
import org.koin.core.parameter.ParametersDefinition

inline fun <reified T : ViewModel> Fragment.viewModel(
        noinline parameters: ParametersDefinition? = null
): Lazy<T> {
    return lazy {
        getViewModel(parameters = parameters)
    }
}
```

**Comment by Pfoerd** [comment] 2022-08-04 05:43
Likely a duplicate of https://github.com/InsertKoinIO/koin/issues/1356

**Comment by arnaudgiuliani** [comment] 2022-08-26 15:15
yes duplicated

**Closed by arnaudgiuliani** 2022-08-26 15:15 UTC
Labels: status:duplicated
