### ISSUE TITLE
Could not instantiate WorkManager in 3.4.0

### ISSUE THREAD

**Issue by tyczj** [InsertKoinIO/koin#1571] opened 2023-04-27 15:15 UTC
**Describe the bug**
When trying to start a work manager task I get a "Cannot instantiate MyWorkManager"

Full error

```
Could not instantiate com.workers.MyWorkManager
 java.lang.NoSuchMethodException: com.workers.MyWorkManager.<init> [class android.content.Context, class androidx.work.WorkerParameters]
at java.lang.Class.getConstructor0(Class.java:2332)
at java.lang.Class.getDeclaredConstructor(Class.java:2170)
at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
```

dont know if this matters any but I disable workmanager startup in my manifest

```
<provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="com.my.package.androidx-startup"
            android:exported="false"
            tools:node="merge">

            <meta-data
                android:name="androidx.work.WorkManagerInitializer"
                android:value="androidx.startup"
                tools:node="remove" />
        </provider>
```

This error happens in koin 3.4.0, when I downgrade the version of koin to 3.3.0 everything works fine

**To Reproduce**
1. Create a work manager
2. Start work manager as a single task
3. See error

**Expected behavior**
Be able to launch a work manager task

**Koin project used and used version:**
`koin-androidx-workmanager version 3.4.0`

**Additional moduleDefinition**
Additional koin modules used are 
koin-android
koin-android-compat
koin-ksp-compiler - v 1.0.3
android work manager version 2.8.1

**Comment by tatocaster** [comment] 2023-04-28 05:26
it is duplicate of the existing issue: #1554

**Comment by arnaudgiuliani** [comment] 2023-05-02 19:07
yep closing it due to duplication

**Closed by arnaudgiuliani** 2023-05-02 19:07 UTC
Labels: status:duplicated
