### ISSUE TITLE
The Constructor DSL could inject parameters via getOrNull()

### ISSUE THREAD

**Issue by gary0707** [InsertKoinIO/koin#1812] opened 2024-03-05 08:24 UTC
**Is your feature request related to a problem? Please describe.**
In my code base, some of constructors use optional (nullable) parameters, which are not resolved correctly when I use the Constructor DSL like:
```kotlin
class FizzClass(val initialValue: Int?)

val someModule = module {
    factoryOf(::FizzClass)
}
```

The `FizzClass` is sometimes inject with a non-null value, but sometimes with null and to make that work I need to go with the classic DSL like:
```kotlin
val someModule = module {
    factory {
        FizzClass(initialValue = getOrNull())
    }
}
```

**Describe the solution you'd like**
It would be great to be able to use the Constructor DSL also with nullable injected params.

**Describe alternatives you've considered**
The only alternative I can see for now is the go with much more verbose classic Koin DSL.

**Target Koin project**
Koin-Core

**Comment by Nek-12** [comment] 2024-04-17 11:22
Duplicate of #1456

**Comment by Nek-12** [comment] 2024-10-02 10:06
God, the return of the dreaded bot

**Closed** 2024-10-12 03:06 UTC
Labels: status:duplicated, status:wontfix, type:improvement
