### ISSUE TITLE
Compose - getViewModel with new parameters doesn't give a new instance - androidx-compose:3.2.2

### ISSUE THREAD

**Issue by oteljazouli-bc** [InsertKoinIO/koin#1477] opened 2022-11-17 21:49 UTC
**Describe the bug**
```
userId?.let {
    ActivityDetail(
        viewModel = getViewModel(
            scope = myScope,
            parameters = {
                println("userId $userId")
                parametersOf(userId) }
        )
    )
} 
```

```
@Composable
fun ActivityDetail(
    viewModel: DetailViewModel
) {
```

I have this setup, when `ActivityDetail(` is called the first time, it gives the right instance with the right `userId`, closing that and calling again with another `userId` keep the same old instance of the viewModel with the old `userId`

I saw from https://github.com/InsertKoinIO/koin/issues/1305 that there was a similar fix for `3.2.1`, I used `3.2.1` and `3.2.2` but still having this issue.

**To Reproduce**
please see the code above

**Expected behavior**
A new viewmodel instance when parameters are different

**Koin project used and used version (please complete the following information):**
"io.insert-koin:koin-androidx-compose:3.2.2"

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by Nek-12** [comment] 2022-11-21 12:38
I'm also facing this issue with any injected dependency, not just the viewModel one.

**Comment by p-fischer** [comment] 2022-12-03 15:25
I'm also facing this issue with a parameterized view model (using the `getViewModel(parameters = { parametersOf(elementId) })` syntax).

If I'm navigating back (Jetpack Compose via `NavController`) and re-enter the screen, the view model is re-created with the correct parameters.

In my scenario, I stay within a single route and only open a dialog, which has its own view model as a parameter.
These dialogs can be opened by clicking on list elements - so the dialog composable and view model get passed different arguments values each time.

Is there a version of Koin, which creates new view model instances?

**Comment by arnaudgiuliani** [comment] 2023-01-09 16:45
did you to upgrade to androidx-compose 3.4.1?

**Comment by lammertw** [comment] 2023-03-14 17:29
I'm having the same issue. Version 3.4.1 does not seem to fix it.

**Comment by snaum47** [comment] 2023-05-08 12:07
We're having the same issue but not with Compose.
Inside our fragment we inject viewmodels with different parameters provided each time. 
What we expect is that since the parameters are different, a new instance should be provided. But that's not the case and the 1st instance with the 1st parameters is provided on all future injections of the viewmodel in the same fragment.

A basic case with the issue is shown below:
`
// the module
fun appModule() = module {
  viewModel { parameters ->
    TestViewModel(parameters.get())
  }
}
// the viewmodel
class TestViewModel(
  val id: UUID
): ViewModel() {

  private val logger = LoggerFactory.getLogger(javaClass)

  fun printId() {
    logger.debug("Printing TestViewModel $id")
  }

}
class SomeFragment : Fragment() {
  override fun onResume() {
    super.onResume()
    initialize()
    initialize()
  }

  private fun initialize() {
    val testViewModel: TestViewModel by viewModel {
      parametersOf(UUID.randomUUID())
    }
    testViewModel.printId()
  }
}
`
What will be printed is:
`
Printing TestViewModel 2e7d1d81-3506-49c6-845b-6f926ab8fa86
Printing TestViewModel 2e7d1d81-3506-49c6-845b-6f926ab8fa86
`
Even though the parameters are different, the first uuid is used for the 2nd print.

**Comment by oteljazouli-bc** [comment] 2023-05-08 12:12
Im not sure about non compose, but for those who do use it, here's the solution

  ```
          viewModel = getViewModel(
                key = uniqueId, // this is what gives a different instance
                parameters = { parametersOf(...) }
            ),
```

**Comment by snaum47** [comment] 2023-05-08 12:27
We had the same issue using fragment as well -> https://github.com/InsertKoinIO/koin/issues/1578

**Comment by lammertw** [comment] 2023-05-23 15:13
The key works when there is no qualifier. Unfortunately the key is ignored when there is a qualifier present.

**Comment by kotya341** [comment] 2023-08-04 15:53
is this problem fixed with [core-3.4.3](https://github.com/InsertKoinIO/koin/blob/main) and `parametersOf is using indexed values + fallback on value for type -`?

**Comment by oteljazouli-bc** [comment] 2023-08-04 16:05
@lammertw a bit late, im not sure why but this works, here using `koin-androidx-compose:3.3.0`

```
viewModel = getViewModel(
        scope = customScope,
         key = selectedTxId,
         parameters = { parametersOf(selectedTxId) }
),
```

**Comment by arnaudgiuliani** [comment] 2023-08-29 12:35
yes, perhaps if there is a VM key, to use it in the name 🤔

**Comment by arnaudgiuliani** [comment] 2023-09-04 10:42
let's see with koin-android 3.5.0 and parameter race condition fix https://github.com/InsertKoinIO/koin/pull/1561 how it goes 👍

**Closed by arnaudgiuliani** 2023-09-04 10:42 UTC
Labels: question

**Comment by IlyaChizhanov** [comment] 2024-10-22 08:30
I used `4.0.0` but still having this issue.

**Comment by akexorcist** [comment] 2025-03-11 10:55
Still having this issue on 4.0.2

Even though assigning a random unique key to the `koinViewModel` method does create a new ViewModel instance, I've found that when the Dialog is dismissed, the Dialog's ViewModel isn't destroyed. This leaves the ViewModel instance in memory and can potentially lead to an out-of-memory issue.

![Image](https://github.com/user-attachments/assets/5554c165-cd6e-405b-b961-378c218f03b6)

This happens because the ViewModel lifecycle is tied to the Activity or Fragment lifecycle that hosts the Compose, not to the Composable lifecycle.

If you'd like to see the example code I used for testing, you can find it at https://github.com/akexorcist/new-viewmodel-in-compose-dialog-issue.
