### ISSUE TITLE
Koin is not compatible with Ktor 3.0.0

### ISSUE THREAD

**Issue by AlejandroYuste** [InsertKoinIO/koin#2027] opened 2024-10-14 11:07 UTC
**Describe the bug**
If the injection is defined as part of a route it will not find the class.

**To Reproduce**
Define something like:

```
fun Route.account() {
    route("/account") {
        val fetchAccountUseCase by inject<FetchAccountUseCase>()
        
        get {
            // whatever
         }
    }
}
```

> java.lang.NoClassDefFoundError: io/ktor/server/routing/RoutingKt
> 	at org.koin.ktor.ext.RouteExtKt.getKoin(RouteExt.kt:74)
> 	at app.presentation.account.AccountKt$account$$inlined$inject$default$1.invoke(RouteExt.kt:76)

**Expected behavior**
Everything should run smoothly.

**Koin module and version:**
 `koin-core:4.0.0`
 `ktor:3.0.0`

**Comment by valeriyo** [comment] 2024-10-16 02:37
Duplicate of https://github.com/InsertKoinIO/koin/issues/1716

**Comment by sschuberth** [comment] 2024-10-25 15:03
> Duplicate of #1716

Indeed, please close this issue @AlejandroYuste.

**Closed** 2024-10-25 15:09 UTC

**Comment by junkeritechnepal** [comment] 2025-03-29 05:37
@AlejandroYuste https://github.com/InsertKoinIO/koin/issues/1716#issuecomment-2763114231

**Comment by junkeritechnepal** [comment] 2025-03-29 05:37
> Duplicate of [#1716](https://github.com/InsertKoinIO/koin/issues/1716)

https://github.com/InsertKoinIO/koin/issues/1716#issuecomment-2763114231
